// <auto-generated />
using System;
using LAB_TH_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LAB_TH_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LAB_TH_API.Models.Authors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Nguyen Van A"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Tran Van B"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Nguyễn Văn C"
                        });
                });

            modelBuilder.Entity("LAB_TH_API.Models.Book_Author", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId");

                    b.HasIndex("AuthorId");

                    b.ToTable("BooksAuthor");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 1,
                            Id = 1
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 2,
                            Id = 2
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 3,
                            Id = 3
                        });
                });

            modelBuilder.Entity("LAB_TH_API.Models.Books", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CoverUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRead")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("PublishersId")
                        .HasColumnType("int");

                    b.Property<int>("Rate")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PublishersId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoverUrl = "url1",
                            DateAdded = new DateTime(2024, 4, 16, 10, 10, 36, 995, DateTimeKind.Local).AddTicks(7247),
                            DateRead = new DateTime(2024, 4, 16, 10, 10, 36, 995, DateTimeKind.Local).AddTicks(7233),
                            Description = "Description for Book 1",
                            Genre = 1,
                            IsRead = true,
                            PublishersId = 1,
                            Rate = 4,
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = 2,
                            CoverUrl = "url2",
                            DateAdded = new DateTime(2024, 4, 16, 10, 10, 36, 995, DateTimeKind.Local).AddTicks(7250),
                            DateRead = new DateTime(2024, 4, 16, 10, 10, 36, 995, DateTimeKind.Local).AddTicks(7249),
                            Description = "Description for Book 2",
                            Genre = 2,
                            IsRead = false,
                            PublishersId = 2,
                            Rate = 3,
                            Title = "Book 2"
                        },
                        new
                        {
                            Id = 3,
                            CoverUrl = "url3",
                            DateAdded = new DateTime(2024, 4, 16, 10, 10, 36, 995, DateTimeKind.Local).AddTicks(7252),
                            DateRead = new DateTime(2024, 4, 16, 10, 10, 36, 995, DateTimeKind.Local).AddTicks(7251),
                            Description = "Description for Book 3",
                            Genre = 2,
                            IsRead = true,
                            PublishersId = 2,
                            Rate = 4,
                            Title = "Book 3"
                        });
                });

            modelBuilder.Entity("LAB_TH_API.Models.Publishers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Publishers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Publisher A"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Publisher B"
                        });
                });

            modelBuilder.Entity("LAB_TH_API.Models.Book_Author", b =>
                {
                    b.HasOne("LAB_TH_API.Models.Authors", "authors")
                        .WithMany("Book_Author")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LAB_TH_API.Models.Books", "books")
                        .WithMany("Book_Author")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("authors");

                    b.Navigation("books");
                });

            modelBuilder.Entity("LAB_TH_API.Models.Books", b =>
                {
                    b.HasOne("LAB_TH_API.Models.Publishers", "publishers")
                        .WithMany("Book")
                        .HasForeignKey("PublishersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("publishers");
                });

            modelBuilder.Entity("LAB_TH_API.Models.Authors", b =>
                {
                    b.Navigation("Book_Author");
                });

            modelBuilder.Entity("LAB_TH_API.Models.Books", b =>
                {
                    b.Navigation("Book_Author");
                });

            modelBuilder.Entity("LAB_TH_API.Models.Publishers", b =>
                {
                    b.Navigation("Book");
                });
#pragma warning restore 612, 618
        }
    }
}
